### ISSUE TITLE
FairyGUI的谷主说打包时不要包含FairyGUI-as3.swc，就不会有兼容问题，可以支持高版本

### ISSUE THREAD

**Issue by yc2768** [qufangliu/Plugin_FairyGUI_Lua#1]
FairyGUI的谷主说打包时不要包含FairyGUI-as3.swc，就不会有兼容问题，可以支持高版本。（本人unity的，不太懂AS）感谢分享，我用Fairygui-Editor 3.7.3 可以导出lua代码

**Comment by qufangliu** [comment]
同用unity，不懂AS。。。。哈哈

这里可能有误解，我是说之前交流群里分享的插件无法正常生成lua代码。
这个项目中的插件是修改后重新build的，所以可以正常使用。
